// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Workshop_Forum_App.Data;

#nullable disable

namespace Workshop_Forum_App.Data.Migrations
{
    [DbContext(typeof(ForumDbContext))]
    partial class ForumDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.15")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Workshop_Forum_App.Data.Models.Post", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasMaxLength(1500)
                        .HasColumnType("nvarchar(1500)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("Posts");

                    b.HasData(
                        new
                        {
                            Id = new Guid("0e3a1df3-48d4-47b0-abf7-b7ee263ac15f"),
                            Content = "Lorem ipsum dolor sit amet,",
                            Title = "My first post"
                        },
                        new
                        {
                            Id = new Guid("f0661842-4f0a-46ad-b684-08f424e0ae9f"),
                            Content = "2 - Lorem ipsum dolor sit amet,",
                            Title = "My second post"
                        },
                        new
                        {
                            Id = new Guid("0034ba7e-75d9-42d6-bda0-c563db1b937c"),
                            Content = "3 - Lorem ipsum dolor sit amet,",
                            Title = "My third post"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
